name: CI # defines name of the workflow

on:
  pull_request:
    branches:
      - main # creates a pull request for the main branch

jobs:
  code-quality-check: # job name
    runs-on: ubuntu-latest # runs on ubuntu
    steps:
      - name: Checkout code # loads the source code
        uses: actions/checkout@v4 # uses the checkout action
        with:
          ref: ${{ github.head_ref }} # Checkout the correct PR branch

      - name: Set up Node.js # installs node version 18.x to use npm and node commands
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies # installs the dependencies
        run: npm ci

      - name: Run linter # runs the linter
        run: npm run lint

      - name: Run format write # runs the format write to apply Prettier formatting
        run: npm run format-write

      - name: Check for format changes # checks if there were changes after format-write
        run: git diff --exit-code || echo "There are format changes"

      - name: Commit and push format changes # commits and pushes the changes if there were any
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "chore: apply prettier formatting"
          git push origin ${{ github.head_ref }} # Push the changes to the current PR branch

      - name: Run tests # runs the tests
        run: npm run test